msg:
  greeting: "안녕하세요. account default"

---

spring:
  profiles: stage
msg:
  greeting: "안녕하세요. account stage"

---

spring:
  profiles: dev
msg:
  greeting: "안녕하세요. account dev"

---

spring:
  profiles: local
msg:
  greeting: "안녕하세요. account local"
  
greeting: "just one"
