devguide:
  greeting: "안녕하세요. account default"

---

spring:
  profiles: stage
devguide:
  greeting: "안녕하세요. account stage"

---

spring:
  profiles: dev
devguide:
  greeting: "안녕하세요. account dev"

---

spring:
  profiles: local
devguide:
  greeting: "HI!. account local"
